1747295461.8526242 [INFO] [launch]: All log files can be found below /home/stas/KNR/Dron_symulacja/mission_lig/2025-05-15-09-51-01-851643-stas-Legion-Y540-15IRH-PG0-10691
1747295461.8527369 [INFO] [launch]: Default logging verbosity is set to INFO
1747295461.9072351 [INFO] [drone_handler-1]: process started with pid [10692]
1747295461.9074719 [INFO] [camera_node-2]: process started with pid [10694]
1747295461.9076245 [INFO] [images_recorder-3]: process started with pid [10696]
1747295461.9077506 [INFO] [aruco_node-4]: process started with pid [10698]
1747295461.9078753 [INFO] [ros_mission_website-5]: process started with pid [10700]
1747295462.1658404 [camera_node-2] [0:44:09.277025628] [10694] [1;32m INFO [1;37mCamera [1;34mcamera_manager.cpp:284 [0mlibcamera v0.1.0
1747295462.2658696 [camera_node-2] [INFO] [1747295462.265472436] [camera]: 
1747295462.2666678 [camera_node-2] >> cameras:
1747295462.2675431 [camera_node-2]    0: Integrated Camera: Integrated C (\_SB_.PCI0.XHC_.RHUB.HS06-6:1.0-5986:2113)
1747295462.2681024 [camera_node-2] [WARN] [1747295462.266085850] [camera]: no camera selected, using default: "\_SB_.PCI0.XHC_.RHUB.HS06-6:1.0-5986:2113"
1747295462.2694850 [camera_node-2] [WARN] [1747295462.266113014] [camera]: set parameter 'camera' to silence this warning
1747295462.2794135 [camera_node-2] [INFO] [1747295462.278778637] [camera]: 
1747295462.2801509 [camera_node-2] >> stream formats:
1747295462.2803190 [camera_node-2]    - MJPEG (320x180 - 1280x720)
1747295462.2804761 [camera_node-2]    - YUYV (320x180 - 1280x720)
1747295462.2806282 [camera_node-2] terminate called after throwing an instance of 'std::runtime_error'
1747295462.2807715 [camera_node-2]   what():  unsupported pixel format "RGB888"
1747295462.7641697 [images_recorder-3] [INFO] [1747295462.763813228] [images_recorder]: camera_topic: camera/image_raw
1747295462.8127232 [images_recorder-3] [INFO] [1747295462.812458452] [images_recorder]: Saving images to saved_images/4
1747295462.8134174 [images_recorder-3] [INFO] [1747295462.813259416] [images_recorder]: video_recorder node created
1747295462.8140311 [images_recorder-3] [INFO] [1747295462.813843282] [images_recorder]: Recording images to directory: saved_images/4
1747295462.8243418 [aruco_node-4] [INFO] [1747295462.824072052] [aruco_node]: Marker size: 0.1
1747295462.8248348 [aruco_node-4] [INFO] [1747295462.824588783] [aruco_node]: Marker type: DICT_4X4_100
1747295462.8252254 [aruco_node-4] [INFO] [1747295462.825098977] [aruco_node]: Image topic: camera/image_raw
1747295462.8259208 [aruco_node-4] [INFO] [1747295462.825767396] [aruco_node]: Intrinsic matrix: [[  1.   0. 320.]
1747295462.8260438 [aruco_node-4]  [  0.   1. 240.]
1747295462.8261495 [aruco_node-4]  [  0.   0.   1.]]
1747295462.8267136 [aruco_node-4] [INFO] [1747295462.826500064] [aruco_node]: Distortion: [0. 0. 0. 0.]
1747295462.8323867 [drone_handler-1] [WARN] [1747295462.832114876] [drone_handler]: DEV MODE is enabled.
1747295462.8329105 [drone_handler-1] [INFO] [1747295462.832718094] [drone_handler]: Connecting with copter at /dev/ttyACM0...
1747295462.8359687 [drone_handler-1] [WARN] [1747295462.835701702] [drone_handler]: Connecting failed with error: [Errno 2] could not open port /dev/ttyACM0: [Errno 2] No such file or directory: '/dev/ttyACM0'
1747295462.8364635 [drone_handler-1] [INFO] [1747295462.836287658] [drone_handler]: Retrying to connect in {3} seconds...
1747295462.9295919 [ros_mission_website-5] [INFO] [1747295462.929363075] [ros_mission_website]: MissionWebsiteClient node created
1747295463.4535339 [ERROR] [camera_node-2]: process has died [pid 10694, exit code -6, cmd '/opt/ros/humble/lib/camera_ros/camera_node --ros-args --params-file /tmp/launch_params_j79n0tfn'].
1747295463.4945219 [ros_mission_website-5] [INFO] [1747295463.494113637] [ros_mission_website]: âœ… Server is available.
1747295463.8135788 [images_recorder-3] [WARN] [1747295463.813286274] [images_recorder]: No frame to save yet
1747295464.1076982 [ros_mission_website-5] [INFO] [1747295464.107486665] [ros_mission_website]: Status telemetry post: 200
1747295464.8136001 [images_recorder-3] [WARN] [1747295464.813283292] [images_recorder]: No frame to save yet
1747295464.8271470 [ros_mission_website-5] [INFO] [1747295464.826939822] [ros_mission_website]: Status telemetry post: 200
1747295465.4389787 [ros_mission_website-5] [INFO] [1747295465.438766516] [ros_mission_website]: Status telemetry post: 200
1747295465.8135316 [images_recorder-3] [WARN] [1747295465.813275031] [images_recorder]: No frame to save yet
1747295465.8392131 [drone_handler-1] [WARN] [1747295465.838996799] [drone_handler]: Connecting failed with error: [Errno 2] could not open port /dev/ttyACM0: [Errno 2] No such file or directory: '/dev/ttyACM0'
1747295465.8395002 [drone_handler-1] [INFO] [1747295465.839326739] [drone_handler]: Retrying to connect in {3} seconds...
1747295466.0542912 [ros_mission_website-5] [INFO] [1747295466.054081745] [ros_mission_website]: Status telemetry post: 200
1747295466.6876271 [ros_mission_website-5] [INFO] [1747295466.687371460] [ros_mission_website]: Status telemetry post: 200
1747295466.8135517 [images_recorder-3] [WARN] [1747295466.813279377] [images_recorder]: No frame to save yet
1747295467.2172031 [ros_mission_website-5] [INFO] [1747295467.216994165] [ros_mission_website]: Status telemetry post: 200
1747295467.8145349 [images_recorder-3] [WARN] [1747295467.814245169] [images_recorder]: No frame to save yet
1747295467.8228943 [ros_mission_website-5] [INFO] [1747295467.822702116] [ros_mission_website]: Status telemetry post: 200
1747295468.4359360 [ros_mission_website-5] [INFO] [1747295468.435702996] [ros_mission_website]: Status telemetry post: 200
1747295468.8135962 [images_recorder-3] [WARN] [1747295468.813301694] [images_recorder]: No frame to save yet
1747295468.8433754 [drone_handler-1] [WARN] [1747295468.843144064] [drone_handler]: Connecting failed with error: [Errno 2] could not open port /dev/ttyACM0: [Errno 2] No such file or directory: '/dev/ttyACM0'
1747295468.8437202 [drone_handler-1] [INFO] [1747295468.843500369] [drone_handler]: Retrying to connect in {3} seconds...
1747295469.0228128 [ros_mission_website-5] [INFO] [1747295469.022549467] [ros_mission_website]: Status telemetry post: 200
1747295469.7880437 [ros_mission_website-5] [INFO] [1747295469.787830205] [ros_mission_website]: Status telemetry post: 200
1747295469.8135478 [images_recorder-3] [WARN] [1747295469.813280960] [images_recorder]: No frame to save yet
1747295470.4554715 [ros_mission_website-5] [INFO] [1747295470.455254750] [ros_mission_website]: Status telemetry post: 200
1747295470.8134773 [images_recorder-3] [WARN] [1747295470.813243257] [images_recorder]: No frame to save yet
1747295471.1739845 [ros_mission_website-5] [INFO] [1747295471.173770431] [ros_mission_website]: Status telemetry post: 200
1747295471.8135664 [images_recorder-3] [WARN] [1747295471.813269527] [images_recorder]: No frame to save yet
1747295471.8463027 [drone_handler-1] [WARN] [1747295471.846055181] [drone_handler]: Connecting failed with error: [Errno 2] could not open port /dev/ttyACM0: [Errno 2] No such file or directory: '/dev/ttyACM0'
1747295471.8467710 [drone_handler-1] [INFO] [1747295471.846651864] [drone_handler]: Retrying to connect in {3} seconds...
1747295471.9087162 [ros_mission_website-5] [INFO] [1747295471.908499200] [ros_mission_website]: Status telemetry post: 200
1747295472.5045955 [ros_mission_website-5] [INFO] [1747295472.504339099] [ros_mission_website]: Status telemetry post: 200
1747295472.8137932 [images_recorder-3] [WARN] [1747295472.813559803] [images_recorder]: No frame to save yet
1747295473.1177058 [ros_mission_website-5] [INFO] [1747295473.117493391] [ros_mission_website]: Status telemetry post: 200
1747295473.8141661 [images_recorder-3] [WARN] [1747295473.813909328] [images_recorder]: No frame to save yet
1747295473.8533680 [ros_mission_website-5] [INFO] [1747295473.853134484] [ros_mission_website]: Status telemetry post: 200
1747295473.9097490 [INFO] [healthcheck-6]: process started with pid [10790]
1747295474.3295887 [healthcheck-6] [INFO] [1747295474.329327283] [drone_healthcheck]: Checking drone_handler services...
1747295474.5673048 [ros_mission_website-5] [INFO] [1747295474.567069538] [ros_mission_website]: Status telemetry post: 200
1747295474.8135068 [images_recorder-3] [WARN] [1747295474.813241931] [images_recorder]: No frame to save yet
1747295474.8505723 [drone_handler-1] [WARN] [1747295474.850256585] [drone_handler]: Connecting failed with error: [Errno 2] could not open port /dev/ttyACM0: [Errno 2] No such file or directory: '/dev/ttyACM0'
1747295474.8509126 [drone_handler-1] [INFO] [1747295474.850739313] [drone_handler]: Retrying to connect in {3} seconds...
1747295475.0998766 [ros_mission_website-5] [INFO] [1747295475.099652147] [ros_mission_website]: Status telemetry post: 200
1747295475.6907911 [ros_mission_website-5] [INFO] [1747295475.690564188] [ros_mission_website]: Status telemetry post: 200
1747295475.8140266 [images_recorder-3] [WARN] [1747295475.813766734] [images_recorder]: No frame to save yet
1747295476.2926283 [ros_mission_website-5] [INFO] [1747295476.292364049] [ros_mission_website]: Status telemetry post: 200
1747295476.8139033 [images_recorder-3] [WARN] [1747295476.813655174] [images_recorder]: No frame to save yet
1747295477.2328939 [ros_mission_website-5] [INFO] [1747295477.232680671] [ros_mission_website]: Status telemetry post: 200
1747295477.8134387 [images_recorder-3] [WARN] [1747295477.813184474] [images_recorder]: No frame to save yet
1747295477.8544891 [drone_handler-1] [WARN] [1747295477.854153499] [drone_handler]: Connecting failed with error: [Errno 2] could not open port /dev/ttyACM0: [Errno 2] No such file or directory: '/dev/ttyACM0'
1747295477.8549914 [drone_handler-1] [INFO] [1747295477.854838547] [drone_handler]: Retrying to connect in {3} seconds...
1747295477.8837082 [ros_mission_website-5] [INFO] [1747295477.883461398] [ros_mission_website]: Status telemetry post: 200
1747295478.4562502 [ros_mission_website-5] [INFO] [1747295478.456012446] [ros_mission_website]: Status telemetry post: 200
1747295478.8134940 [images_recorder-3] [WARN] [1747295478.813203913] [images_recorder]: No frame to save yet
1747295479.0715694 [ros_mission_website-5] [INFO] [1747295479.071304660] [ros_mission_website]: Status telemetry post: 200
1747295479.3313191 [healthcheck-6] [INFO] [1747295479.331091100] [drone_healthcheck]: Checking camera frames...
1747295479.6894464 [ros_mission_website-5] [INFO] [1747295479.689227273] [ros_mission_website]: Status telemetry post: 200
1747295479.8135262 [images_recorder-3] [WARN] [1747295479.813266273] [images_recorder]: No frame to save yet
1747295480.3881538 [ros_mission_website-5] [INFO] [1747295480.387935708] [ros_mission_website]: Status telemetry post: 200
1747295480.8134191 [images_recorder-3] [WARN] [1747295480.813192042] [images_recorder]: No frame to save yet
1747295480.8585784 [drone_handler-1] [WARN] [1747295480.858278529] [drone_handler]: Connecting failed with error: [Errno 2] could not open port /dev/ttyACM0: [Errno 2] No such file or directory: '/dev/ttyACM0'
1747295480.8590243 [drone_handler-1] [INFO] [1747295480.858899240] [drone_handler]: Retrying to connect in {3} seconds...
1747295481.0206790 [ros_mission_website-5] [INFO] [1747295481.020015563] [ros_mission_website]: Status telemetry post: 200
1747295481.5553586 [ros_mission_website-5] [INFO] [1747295481.555139659] [ros_mission_website]: Status telemetry post: 200
1747295481.8134096 [images_recorder-3] [WARN] [1747295481.813186948] [images_recorder]: No frame to save yet
1747295482.1416945 [ros_mission_website-5] [INFO] [1747295482.141522625] [ros_mission_website]: Status telemetry post: 200
1747295482.3337808 [healthcheck-6] [INFO] [1747295482.333567889] [drone_healthcheck]: Checking telemetry topic...
1747295482.7618175 [ros_mission_website-5] [INFO] [1747295482.761579496] [ros_mission_website]: Status telemetry post: 200
1747295482.8134680 [images_recorder-3] [WARN] [1747295482.813176130] [images_recorder]: No frame to save yet
1747295483.3734901 [ros_mission_website-5] [INFO] [1747295483.373244333] [ros_mission_website]: Status telemetry post: 200
1747295483.8141539 [images_recorder-3] [WARN] [1747295483.813906707] [images_recorder]: No frame to save yet
1747295483.8625104 [drone_handler-1] [WARN] [1747295483.862228050] [drone_handler]: Connecting failed with error: [Errno 2] could not open port /dev/ttyACM0: [Errno 2] No such file or directory: '/dev/ttyACM0'
1747295483.8630190 [drone_handler-1] [INFO] [1747295483.862886257] [drone_handler]: Retrying to connect in {3} seconds...
1747295484.0886531 [ros_mission_website-5] [INFO] [1747295484.088445890] [ros_mission_website]: Status telemetry post: 200
1747295484.6976781 [ros_mission_website-5] [INFO] [1747295484.697438889] [ros_mission_website]: Status telemetry post: 200
1747295484.8135345 [images_recorder-3] [WARN] [1747295484.813278816] [images_recorder]: No frame to save yet
1747295485.3198762 [ros_mission_website-5] [INFO] [1747295485.319629592] [ros_mission_website]: Status telemetry post: 200
1747295485.8134792 [images_recorder-3] [WARN] [1747295485.813216432] [images_recorder]: No frame to save yet
1747295485.9473071 [ros_mission_website-5] [INFO] [1747295485.947056942] [ros_mission_website]: Status telemetry post: 200
1747295486.5515089 [ros_mission_website-5] [INFO] [1747295486.551293259] [ros_mission_website]: Status telemetry post: 200
1747295486.8134091 [images_recorder-3] [WARN] [1747295486.813192438] [images_recorder]: No frame to save yet
1747295486.8665965 [drone_handler-1] [WARN] [1747295486.866254645] [drone_handler]: Connecting failed with error: [Errno 2] could not open port /dev/ttyACM0: [Errno 2] No such file or directory: '/dev/ttyACM0'
1747295486.8671241 [drone_handler-1] [INFO] [1747295486.867004468] [drone_handler]: Retrying to connect in {3} seconds...
1747295487.0755889 [ros_mission_website-5] [INFO] [1747295487.075150434] [ros_mission_website]: Status telemetry post: 200
1747295487.3391309 [healthcheck-6] [INFO] [1747295487.338895390] [drone_healthcheck]: Checking running nodes...
1747295487.3394814 [healthcheck-6] [INFO] [1747295487.339324088] [drone_healthcheck]: Checking web node connection...
1747295487.3397839 [healthcheck-6] [INFO] [1747295487.339649823] [drone_healthcheck]: Checking 'post_log_to_web' service...
1747295487.5729744 [ros_mission_website-5] [INFO] [1747295487.572752027] [ros_mission_website]: Status telemetry post: 200
1747295487.8136384 [images_recorder-3] [WARN] [1747295487.813393542] [images_recorder]: No frame to save yet
1747295488.1083610 [ros_mission_website-5] [INFO] [1747295488.108144691] [ros_mission_website]: Status telemetry post: 200
1747295488.6460381 [ros_mission_website-5] [INFO] [1747295488.645769640] [ros_mission_website]: Successfully posted log: {'message': 'Healthcheck test log', 'level': 'info'}
1747295488.6478438 [healthcheck-6] [INFO] [1747295488.647637340] [drone_healthcheck]: +---------+---------------------------------------------------------------------+
1747295488.6479864 [healthcheck-6] | Status  |                               Message                               |
1747295488.6480441 [healthcheck-6] +---------+---------------------------------------------------------------------+
1747295488.6481237 [healthcheck-6] | [32mSUCCESS[0m |                Service 'get_attitude' is available.                 |
1747295488.6481934 [healthcheck-6] | [32mSUCCESS[0m |                    Node 'aruco_node' is running.                    |
1747295488.6482415 [healthcheck-6] | [32mSUCCESS[0m |               Node 'ros_mission_website' is running.                |
1747295488.6483071 [healthcheck-6] | [32mSUCCESS[0m |               Service 'post_log_to_web' is available.               |
1747295488.6483843 [healthcheck-6] | [32mSUCCESS[0m |          Service 'post_log_to_web' responded successfully.          |
1747295488.6484585 [healthcheck-6] |  [31mERROR[0m  | Service 'get_attitude' did not respond. (drone_handler not healthy) |
1747295488.6485081 [healthcheck-6] |  [31mERROR[0m  |           No frames received on 'camera/image_raw' topic.           |
1747295488.6485796 [healthcheck-6] |  [31mERROR[0m  |          No telemetry data received on 'telemetry' topic.           |
1747295488.6486542 [healthcheck-6] +---------+---------------------------------------------------------------------+
1747295488.7900472 [INFO] [healthcheck-6]: process has finished cleanly [pid 10790]
1747295488.8133903 [images_recorder-3] [WARN] [1747295488.813173431] [images_recorder]: No frame to save yet
1747295489.1387720 [ros_mission_website-5] [INFO] [1747295489.138556162] [ros_mission_website]: Status telemetry post: 200
1747295489.7318161 [ros_mission_website-5] [INFO] [1747295489.731581623] [ros_mission_website]: Status telemetry post: 200
1747295489.8135960 [images_recorder-3] [WARN] [1747295489.813300746] [images_recorder]: No frame to save yet
1747295489.8706012 [drone_handler-1] [WARN] [1747295489.870267630] [drone_handler]: Connecting failed with error: [Errno 2] could not open port /dev/ttyACM0: [Errno 2] No such file or directory: '/dev/ttyACM0'
1747295489.8711360 [drone_handler-1] [INFO] [1747295489.871014214] [drone_handler]: Retrying to connect in {3} seconds...
1747295490.2626135 [ros_mission_website-5] [INFO] [1747295490.262352353] [ros_mission_website]: Status telemetry post: 200
1747295490.8134890 [images_recorder-3] [WARN] [1747295490.813236680] [images_recorder]: No frame to save yet
1747295490.8404672 [ros_mission_website-5] [INFO] [1747295490.840208010] [ros_mission_website]: Status telemetry post: 200
1747295491.3546672 [ros_mission_website-5] [INFO] [1747295491.354448950] [ros_mission_website]: Status telemetry post: 200
1747295491.8134277 [images_recorder-3] [WARN] [1747295491.813189604] [images_recorder]: No frame to save yet
1747295491.9767361 [ros_mission_website-5] [INFO] [1747295491.976515077] [ros_mission_website]: Status telemetry post: 200
1747295492.7562962 [ros_mission_website-5] [INFO] [1747295492.756075665] [ros_mission_website]: Status telemetry post: 200
1747295492.8137279 [images_recorder-3] [WARN] [1747295492.813544704] [images_recorder]: No frame to save yet
1747295492.8745754 [drone_handler-1] [WARN] [1747295492.874233902] [drone_handler]: Connecting failed with error: [Errno 2] could not open port /dev/ttyACM0: [Errno 2] No such file or directory: '/dev/ttyACM0'
1747295492.8750548 [drone_handler-1] [INFO] [1747295492.874912985] [drone_handler]: Retrying to connect in {3} seconds...
1747295493.2650259 [ros_mission_website-5] [INFO] [1747295493.264801449] [ros_mission_website]: Status telemetry post: 200
1747295493.8135519 [images_recorder-3] [WARN] [1747295493.813257390] [images_recorder]: No frame to save yet
1747295493.8173738 [ros_mission_website-5] [INFO] [1747295493.817204429] [ros_mission_website]: Status telemetry post: 200
1747295494.3730693 [ros_mission_website-5] [INFO] [1747295494.372850248] [ros_mission_website]: Status telemetry post: 200
1747295494.6092219 [WARNING] [launch]: user interrupted with ctrl-c (SIGINT)
1747295494.6108277 [drone_handler-1] Traceback (most recent call last):
1747295494.6109364 [drone_handler-1]   File "/home/stas/.local/lib/python3.10/site-packages/serial/serialposix.py", line 322, in open
1747295494.6110005 [drone_handler-1]     self.fd = os.open(self.portstr, os.O_RDWR | os.O_NOCTTY | os.O_NONBLOCK)
1747295494.6110556 [drone_handler-1] FileNotFoundError: [Errno 2] No such file or directory: '/dev/ttyACM0'
1747295494.6111066 [drone_handler-1] 
1747295494.6111619 [drone_handler-1] During handling of the above exception, another exception occurred:
1747295494.6112199 [drone_handler-1] 
1747295494.6112833 [drone_handler-1] Traceback (most recent call last):
1747295494.6113470 [drone_handler-1]   File "/home/stas/KNR/Dron_symulacja/install/drone_hardware/lib/python3.10/site-packages/drone_hardware/drone_handler.py", line 83, in __init__
1747295494.6114101 [drone_handler-1]     self.vehicle = connect(connection_string, baud=57600, wait_ready=False)
1747295494.6114831 [drone_handler-1]   File "/usr/local/lib/python3.10/dist-packages/dronekit/__init__.py", line 3159, in connect
1747295494.6115489 [drone_handler-1]     handler = MAVConnection(ip, baud=baud, source_system=source_system, source_component=source_component, use_native=use_native)
1747295494.6116223 [drone_handler-1]   File "/usr/local/lib/python3.10/dist-packages/dronekit/mavlink.py", line 130, in __init__
1747295494.6116848 [drone_handler-1]     self.master = mavutil.mavlink_connection(ip, baud=baud, source_system=source_system, source_component=source_component)
1747295494.6117463 [drone_handler-1]   File "/home/stas/.local/lib/python3.10/site-packages/pymavlink/mavutil.py", line 1823, in mavlink_connection
1747295494.6121867 [images_recorder-3] Traceback (most recent call last):
1747295494.6122968 [images_recorder-3]   File "/home/stas/KNR/Dron_symulacja/install/drone_camera/lib/drone_camera/images_recorder", line 33, in <module>
1747295494.6123950 [images_recorder-3]     sys.exit(load_entry_point('drone-camera==0.0.0', 'console_scripts', 'images_recorder')())
1747295494.6125062 [images_recorder-3]   File "/home/stas/KNR/Dron_symulacja/install/drone_camera/lib/python3.10/site-packages/drone_camera/images_recorder.py", line 66, in main
1747295494.6126039 [images_recorder-3]     rclpy.spin(images_recorder)
1747295494.6126981 [images_recorder-3]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/__init__.py", line 226, in spin
1747295494.6127937 [images_recorder-3]     executor.spin_once()
1747295494.6128895 [images_recorder-3]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 751, in spin_once
1747295494.6129799 [images_recorder-3]     self._spin_once_impl(timeout_sec)
1747295494.6130414 [images_recorder-3]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 740, in _spin_once_impl
1747295494.6131032 [images_recorder-3]     handler, entity, node = self.wait_for_ready_callbacks(timeout_sec=timeout_sec)
1747295494.6131644 [images_recorder-3]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 723, in wait_for_ready_callbacks
1747295494.6132267 [images_recorder-3]     return next(self._cb_iter)
1747295494.6132879 [images_recorder-3]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 620, in _wait_for_ready_callbacks
1747295494.6133494 [images_recorder-3]     wait_set.wait(timeout_nsec)
1747295494.6134102 [images_recorder-3] KeyboardInterrupt
1747295494.6137555 [aruco_node-4] Traceback (most recent call last):
1747295494.6138635 [aruco_node-4]   File "/home/stas/KNR/Dron_symulacja/install/ros2_aruco/lib/ros2_aruco/aruco_node", line 33, in <module>
1747295494.6139359 [aruco_node-4]     sys.exit(load_entry_point('ros2-aruco==0.1.0', 'console_scripts', 'aruco_node')())
1747295494.6140058 [aruco_node-4]   File "/home/stas/KNR/Dron_symulacja/install/ros2_aruco/lib/python3.10/site-packages/ros2_aruco/aruco_node.py", line 193, in main
1747295494.6140754 [aruco_node-4]     rclpy.spin(node)
1747295494.6141448 [aruco_node-4]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/__init__.py", line 226, in spin
1747295494.6142137 [aruco_node-4]     executor.spin_once()
1747295494.6142826 [aruco_node-4]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 751, in spin_once
1747295494.6143510 [aruco_node-4]     self._spin_once_impl(timeout_sec)
1747295494.6144199 [aruco_node-4]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 740, in _spin_once_impl
1747295494.6145058 [aruco_node-4]     handler, entity, node = self.wait_for_ready_callbacks(timeout_sec=timeout_sec)
1747295494.6145756 [aruco_node-4]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 723, in wait_for_ready_callbacks
1747295494.6146438 [aruco_node-4]     return next(self._cb_iter)
1747295494.6147120 [aruco_node-4]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 620, in _wait_for_ready_callbacks
1747295494.6148143 [aruco_node-4]     wait_set.wait(timeout_nsec)
1747295494.6149008 [aruco_node-4] KeyboardInterrupt
1747295494.6152465 [ros_mission_website-5] Traceback (most recent call last):
1747295494.6153421 [ros_mission_website-5]   File "/home/stas/KNR/Dron_symulacja/install/drone_web/lib/drone_web/ros_mission_website", line 33, in <module>
1747295494.6154444 [ros_mission_website-5]     sys.exit(load_entry_point('drone-web==0.0.0', 'console_scripts', 'ros_mission_website')())
1747295494.6155410 [ros_mission_website-5]   File "/home/stas/KNR/Dron_symulacja/install/drone_web/lib/python3.10/site-packages/drone_web/ros_mission_website.py", line 142, in main
1747295494.6156237 [ros_mission_website-5]     rclpy.spin(mission_website_client)
1747295494.6157041 [ros_mission_website-5]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/__init__.py", line 226, in spin
1747295494.6157980 [ros_mission_website-5]     executor.spin_once()
1747295494.6158741 [ros_mission_website-5]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 751, in spin_once
1747295494.6159501 [ros_mission_website-5]     self._spin_once_impl(timeout_sec)
1747295494.6160302 [ros_mission_website-5]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 746, in _spin_once_impl
1747295494.6161010 [ros_mission_website-5]     handler()
1747295494.6161830 [ros_mission_website-5]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/task.py", line 254, in __call__
1747295494.6162519 [ros_mission_website-5]     self._handler.send(None)
1747295494.6163206 [ros_mission_website-5]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 447, in handler
1747295494.6163890 [ros_mission_website-5]     await call_coroutine(entity, arg)
1747295494.6164651 [ros_mission_website-5]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 361, in _execute_timer
1747295494.6165392 [ros_mission_website-5]     await await_or_execute(tmr.callback)
1747295494.6166077 [ros_mission_website-5]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 107, in await_or_execute
1747295494.6169591 [ros_mission_website-5]     return callback(*args)
1747295494.6170464 [ros_mission_website-5]   File "/home/stas/KNR/Dron_symulacja/install/drone_web/lib/python3.10/site-packages/drone_web/ros_mission_website.py", line 112, in post_all_to_server
1747295494.6171236 [ros_mission_website-5]     self.post_telemetry_to_server()
1747295494.6171987 [ros_mission_website-5]   File "/home/stas/KNR/Dron_symulacja/install/drone_web/lib/python3.10/site-packages/drone_web/ros_mission_website.py", line 105, in post_telemetry_to_server
1747295494.6172731 [ros_mission_website-5]     response = requests.post(f"{self.web_app_base_url}/api/status", json=self.current_telemetry)
1747295494.6173480 [ros_mission_website-5]   File "/usr/lib/python3/dist-packages/requests/api.py", line 119, in post
1747295494.6174214 [ros_mission_website-5]     return request('post', url, data=data, json=json, **kwargs)
1747295494.6175084 [ros_mission_website-5]   File "/usr/lib/python3/dist-packages/requests/api.py", line 61, in request
1747295494.6175833 [ros_mission_website-5]     return session.request(method=method, url=url, **kwargs)
1747295494.6176574 [ros_mission_website-5]   File "/usr/lib/python3/dist-packages/requests/sessions.py", line 544, in request
1747295494.6180220 [drone_handler-1]     return mavserial(device,
1747295494.6181040 [drone_handler-1]   File "/home/stas/.local/lib/python3.10/site-packages/pymavlink/mavutil.py", line 971, in __init__
1747295494.6181746 [drone_handler-1]     raise e
1747295494.6182427 [drone_handler-1]   File "/home/stas/.local/lib/python3.10/site-packages/pymavlink/mavutil.py", line 967, in __init__
1747295494.6184731 [ros_mission_website-5]     resp = self.send(prep, **send_kwargs)
1747295494.6185586 [ros_mission_website-5]   File "/usr/lib/python3/dist-packages/requests/sessions.py", line 657, in send
1747295494.6186273 [ros_mission_website-5]     r = adapter.send(request, **kwargs)
1747295494.6186941 [ros_mission_website-5]   File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
1747295494.6187749 [ros_mission_website-5]     resp = conn.urlopen(
1747295494.6188657 [ros_mission_website-5]   File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 700, in urlopen
1747295494.6189389 [ros_mission_website-5]     httplib_response = self._make_request(
1747295494.6190102 [ros_mission_website-5]   File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 383, in _make_request
1747295494.6190822 [ros_mission_website-5]     self._validate_conn(conn)
1747295494.6191547 [ros_mission_website-5]   File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 1017, in _validate_conn
1747295494.6192267 [ros_mission_website-5]     conn.connect()
1747295494.6192985 [ros_mission_website-5]   File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 411, in connect
1747295494.6193707 [ros_mission_website-5]     self.sock = ssl_wrap_socket(
1747295494.6194422 [ros_mission_website-5]   File "/usr/lib/python3/dist-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
1747295494.6195264 [ros_mission_website-5]     ssl_sock = _ssl_wrap_socket_impl(
1747295494.6195989 [ros_mission_website-5]   File "/usr/lib/python3/dist-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
1747295494.6196709 [ros_mission_website-5]     return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
1747295494.6197422 [ros_mission_website-5]   File "/usr/lib/python3.10/ssl.py", line 513, in wrap_socket
1747295494.6201034 [drone_handler-1]     self.port = serial.Serial(self.device, 1200, timeout=0,
1747295494.6201863 [drone_handler-1]   File "/home/stas/.local/lib/python3.10/site-packages/serial/serialutil.py", line 244, in __init__
1747295494.6202595 [drone_handler-1]     self.open()
1747295494.6203310 [drone_handler-1]   File "/home/stas/.local/lib/python3.10/site-packages/serial/serialposix.py", line 325, in open
1747295494.6204016 [drone_handler-1]     raise SerialException(msg.errno, "could not open port {}: {}".format(self._port, msg))
1747295494.6204839 [drone_handler-1] serial.serialutil.SerialException: [Errno 2] could not open port /dev/ttyACM0: [Errno 2] No such file or directory: '/dev/ttyACM0'
1747295494.6205552 [drone_handler-1] 
1747295494.6206253 [drone_handler-1] During handling of the above exception, another exception occurred:
1747295494.6206946 [drone_handler-1] 
1747295494.6207635 [drone_handler-1] Traceback (most recent call last):
1747295494.6208441 [drone_handler-1]   File "/home/stas/KNR/Dron_symulacja/install/drone_hardware/lib/drone_hardware/drone_handler", line 33, in <module>
1747295494.6209071 [drone_handler-1]     sys.exit(load_entry_point('drone-hardware==0.0.0', 'console_scripts', 'drone_handler')())
1747295494.6209714 [drone_handler-1]   File "/home/stas/KNR/Dron_symulacja/install/drone_hardware/lib/python3.10/site-packages/drone_hardware/drone_handler.py", line 523, in main
1747295494.6210351 [drone_handler-1]     drone = DroneHandler()
1747295494.6210980 [drone_handler-1]   File "/home/stas/KNR/Dron_symulacja/install/drone_hardware/lib/python3.10/site-packages/drone_hardware/drone_handler.py", line 87, in __init__
1747295494.6211612 [drone_handler-1]     time.sleep(3)
1747295494.6212237 [drone_handler-1] KeyboardInterrupt
1747295494.6214817 [ros_mission_website-5]     return self.sslsocket_class._create(
1747295494.6215613 [ros_mission_website-5]   File "/usr/lib/python3.10/ssl.py", line 1100, in _create
1747295494.6216249 [ros_mission_website-5]     self.do_handshake()
1747295494.6216879 [ros_mission_website-5]   File "/usr/lib/python3.10/ssl.py", line 1371, in do_handshake
1747295494.6217504 [ros_mission_website-5]     self._sslobj.do_handshake()
1747295494.6218390 [ros_mission_website-5] KeyboardInterrupt
1747295494.6840811 [ERROR] [aruco_node-4]: process has died [pid 10698, exit code -2, cmd '/home/stas/KNR/Dron_symulacja/install/ros2_aruco/lib/ros2_aruco/aruco_node --ros-args --params-file /tmp/launch_params_6l1ghjl9'].
1747295494.6846344 [ERROR] [images_recorder-3]: process has died [pid 10696, exit code -2, cmd '/home/stas/KNR/Dron_symulacja/install/drone_camera/lib/drone_camera/images_recorder --ros-args --params-file /tmp/launch_params_lgo2k6q0'].
1747295494.6937699 [ERROR] [ros_mission_website-5]: process has died [pid 10700, exit code -2, cmd '/home/stas/KNR/Dron_symulacja/install/drone_web/lib/drone_web/ros_mission_website --ros-args --params-file /tmp/launch_params_zozn9nk0'].
1747295494.7013113 [ERROR] [drone_handler-1]: process has died [pid 10692, exit code -2, cmd '/home/stas/KNR/Dron_symulacja/install/drone_hardware/lib/drone_hardware/drone_handler --ros-args --params-file /tmp/launch_params_729g594t'].
